services:

  mysql:
    image: mysql:8.4.11
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATA_DIR: ${MYSQL_DATA_DIR}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    networks:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.2
    container_name: keycloak
    restart: unless-stopped
    command: start
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      KC_DB_USERNAME: ${MYSQL_USER}
      KC_DB_PASSWORD: ${MYSQL_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HOSTNAME: ${HOST}
      KC_HTTP_ENABLED: 'true'
      KC_PROXY_HEADERS: xforwarded
    networks:
      - keycloak
      - proxy
    depends_on:
      - mysql
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.rule=Host(`${HOST}`)
      - traefik.http.routers.keycloak.entrypoints=websecure
      - traefik.http.routers.keycloak.tls.certresolver=letsencrypt
      - traefik.http.services.keycloak.loadbalancer.server.port=8080

networks:
  keycloak:
  proxy:
    external: true
