version: '3'

services:

  portainer:
    image: portainer/portainer:1.22.2
    environment:
      - HOST
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - traefik.frontend.rule=Host:portainer-sso.${HOST}
      - traefik.port=9000
    networks:
      - proxy

  traefik:
    image: traefik:1.7.18
    container_name: traefik
    environment:
      - HOST
    command: --docker --docker.domain=docker-sso.${HOST}
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/gendercomics/auth-server/traefik_${HOST}.toml:/traefik.toml
      - /var/gendercomics/auth-server/acme.json:/acme.json
    labels:
      - traefik.frontend.rule=Host:traefik-sso.${HOST}
      - traefik.port=8080
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATA_DIR: ${MYSQL_DATA_DIR}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    networks:
      - proxy
    ports:
      - 3306:3306

  keycloak:
    image: jboss/keycloak:7.0.0
    container_name: keycloak
    restart: unless-stopped
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    networks:
      - proxy
    ports:
      - 9090:9090
    depends_on:
      - mysql
    labels:
      - traefik.frontend.rule=Host:${HOST}
      - traefik.port=9090

volumes:
  portainer_data:

networks:
  proxy:
    external: true