api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true

certificatesResolvers:
  http:
    acme:
      email: michael.litschauer@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: http